### ISSUE TITLE
Remove the need to manually hit the reloadsheetdata endpoint

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#100]
Right now this is the last manual step in the update process that takes places outside of the google sheet. would be great to automate it so it fires right before the data.json crontab, eg on the :04 and :09

**Comment by 4kbt** [comment]
Is it enough to cron a curl / wget , etc. request?

**Comment by r-pop** [comment]
Actually... data vols think this is a feature, gives safety in case of sheet edit human error.
