### ISSUE TITLE
Automate importing from other PPE projects

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#101]
The PPE distribution cross-project slack is in agreement that job 1 is to start importing data from each other. I have communicated this to all of them:

Ok, we are still working on how to unblock sending data into findthemasks.com - our eng likely need to help with integrations. but to get our data out via code, please read from http://findthemasks.com/data.json . This is the moderated subset of our sheet. It updates every 5 minutes.

I would like us to start importing from others. Top pri is https://docs.google.com/spreadsheets/d/1txEanDkIrJ5GNfSk-zlXkTlB-bQPNRN_Y69qEwmdme8/htmlview?fbclid=IwAR1A6TrHCQ9TttNJbb1kB6b2Xot4DCem-z6DVXUR4V5qToUboOr-50D7h6g&sle=true#

Yesterday @cchang-adi did a huge manual import, but ongoing import is needed. Would like an engineer to pick up this task.

If someone can also represent us in the cross-project import/export chatter and help unblock others who want to send us data, that would be ideal.

**Comment by r-pop** [comment]
Cross-project slack: https://join.slack.com/t/ppe-interteam/shared_invite/zt-cy0b70tj-iXJpwL03F7k~UGbXotZ4Nw

**Comment by cchang-adi** [comment]
Happy to continue manual importing until we build a solution
