### ISSUE TITLE
Design: Improve visibility of donation site list for new visitors

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#103]
Received feedback from another project that our site is dire/doom-y and could be improved by 
1) moving a jump to donate button above the fold (and above the very dire tweet embeds)
2) mentioning that "A consortium of doctors, hospitals, institutions and grassroots efforts are working together to address the need." In future this will expand to link the consortium page, but it doesn't exist yet.

**Comment by r-pop** [comment]
I'd like to see some mock up options for 1

**Comment by VaroonJain-VJ** [comment]
This isn't worth spending too much time on at all. In the short term, Rachel your suggestion to augment with link and mention of centralized efforts and institutions spinning up may help greatly. 

One major point is MDs do NOT recommend individuals calling hospital charge nurses right now -- hospitals are absolutely overwhelmed.

I suggest editing the "How to donate" content to include a new #1.
#1 "Browse through the list of donation sites below. If a site is available near you, follow the drop-off instructions and donate as soon as you can."
#2 "If you do not see a collection center near you - check out getusppe.org/ for additional info on how you can help."

Can we do that? Or something similar?

**Comment by r-pop** [comment]
I'm ok with that update to the instructions. Ack needing to stop the nurse
calls.

Is getusppe ready for traffic? I still saw stubbed out content, broken
links as of an hour ago.

**Comment by VaroonJain-VJ** [comment]
I believe they are...best landing page is prob http://getusppe.org/give

**Comment by r-pop** [comment]
I have addressed the change in instructions (no more calling charge nurses!) and linked getusppe.org/give for uncovered regions.

Still to do: 
1. link to the donation site section (need to add anchor)
2. mention of coordination with other efforts

**Comment by r-pop** [comment]
Added jump link from top of page to donation/add a site section
