### ISSUE TITLE
iframe/embed: Generate isolated version of provider listing, linkable/filter by state

### ISSUE THREAD

**Issue by patricknelson** [r-pop/findthemasks#113]
**Include:**
- Prominent but non invasive info on how to add/change/remove healthcare providers.
- How to donate heading (expandible?)
- Filters (state/accepted items)
- Actual provider listing
- Attribution at bottom: "By findthemasks.com" (or similar)

**NOTE:** I will make changes as requirements change, or simply comment below.

---

**Prototype URL now live at: https://findthemasks.com/give.html**

**Comment by r-pop** [comment]
Graeme, this is same thing I chatted about just now as give.html

instead of our who we are link, can it say "by findthemasks.com" at the bottom

**Comment by r-pop** [comment]
This is done.

**Comment by patricknelson** [comment]
Woo! And I presume @Shuhanhe1 will add this on his end? At https://getusppe.org/give/

- How to donate heading (expandible?)

**Comment by patricknelson** [comment]
Linking relevant PR #111

**Comment by Shuhanhe1** [comment]
yes that is correct!
can you clarify how to donate heading?
Shuhan He

**Comment by patricknelson** [comment]
This section on the findthemask.com site. Ideally if we’re showing large amounts of folks WHERE to donate we need to insure they’re properly informed on HOW 😁

![5EFC6858-3B05-4093-A7C4-9D1533026104](https://user-images.githubusercontent.com/4269377/77273613-456b8500-6c71-11ea-800b-f36f73af8a45.jpeg)

**Comment by r-pop** [comment]
On the call, shuhan had his own content for that I thought, that also
explained what each type of ppe was.

If you want us to include how to donate in the iframe we can do that.

**Comment by Shuhanhe1** [comment]
yes we currently use the CMS to give that info instead of the iframe. I
would keep the iframe to just the information

[image: image.png]
Shuhan He
