### ISSUE TITLE
Map: Prevent multiple pin-balloons from being open simultaneously

### ISSUE THREAD

**Issue by 4kbt** [r-pop/findthemasks#116]
In the beta version, every time a user clicks on a pin, a pin-balloon opens with the hospital information. An arbitrary number of balloons can be opened simultaneously, and the user must close each one individually.

It seems more intuitive/expected to have the open balloon close if the user clicks on a second pin?

**Comment by patricknelson** [comment]
This ticket should be closed, as #123 is now merged 😄
