### ISSUE TITLE
Automate geocoding of donation site address data

### ISSUE THREAD

**Issue by susanashlock** [r-pop/findthemasks#118]
Currently there are two columns in the spreadsheet for "Lat" and "Lng".  I've been copying the un-geocoded addresses into a separate sheet and running an Apps Script to geocode the new addresses, then pasting the latitude and longitudes into the spreadsheet.

I've been doing this to avoid running out of geocoding quota, which is easy to do.  (Without a premium plan, I ran out of quota for the day with one account with just 800 geocoding calls.)  Note that I can't use my 'free trial' Maps API account in Apps Script.  Only a premium plan can do this
I want to avoid using a formula (implemented in Apps Script) in the spreadsheet that will run every time someone opens the sheet.

Possible ways to automate this:
1) Add a button to the spreadsheet that will run a script to find un-geocoded addresses and geocode them and add the lat/lngs to the correct cells.
2) Add logic to the sheet to (somehow) only run formula logic if the geocoding result is empty.

I believe #1 should be possible. No idea about #2.

**Comment by patricknelson** [comment]
If you haven't already, join us on slack!


ppe-interteam.slack.com (http://tiny.cc/PPEinterteamSlack)

#proj-database channel

**Comment by susanashlock** [comment]
Update: I'm working on this now, have made good progress; with luck should have something live in the next hour.

**Comment by patricknelson** [comment]
What’s the mechanism for this? Is this associated with a pull request? I don’t see a note in this ticket about it. Also, checked the spreadsheet and still seeing lots of entries missing lat/long. Got details on how this was implemented? Thanks for the work!

**Comment by patricknelson** [comment]
Oops, nvm. Could just be that this is actively being updated. I’m on my iPad so my app may have limited functionality (in case there’s a button). It does look like many of the lat/long coords are being populated now (only one missing at the time I’m writing this and I’m sure it’ll drop in soon maybe).

**Comment by susanashlock** [comment]
I documented how this works in the wiki and am pasting here for reference:

Addresses are stored in the "Street address for dropoffs"? column of the spreadsheet.

An Apps Script called "fillInGeocodes" automatically runs every 10 minutes to fill in data in the Lat and Lng columns.

You can also force this script to run. To do so from the spreadsheet, open "Tools", then "Script Editor". You should see a dropdown with a list of functions. Select "fillInGeocodes", then click on the "run" button (looks like a "play" button). Go back to the sheet and you should see the Lat and Lng cells filled in!

Unfortunately, we hit the "ran geocoding too many times in one day" error overnight.  I'll log a separate issue for that.
