### ISSUE TITLE
Link for people who can't find a hospital no longer makes sense

### ISSUE THREAD

**Issue by raindrift** [r-pop/findthemasks#124]
There's a link on the site: "If there's not a site near you, visit our friends at getmeppe.org to let them know what you have available."

The link points to GetUsPPE, which now just embeds findthemasks.

We could instead link to or embed the PPELink donation form: https://ppelink.wordpress.com/ppe-donations/

Our existing volunteers can then find donation sites for people who fill it out, and create hospital records for whatever hospital they find for them.

**Comment by r-pop** [comment]
Let's do that. Great catch.

**Comment by r-pop** [comment]
Link please, embed will push content too far down.
