### ISSUE TITLE
Design: within listings for a large city, it's hard to scan and see the different hospitals

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#13]
SF, Seattle have this issue so far

**Comment by yauwong** [comment]
I’m not technically inclined so don’t know how hard this would be, but what about adding a map to the site? If there are lots of hospitals in a city, I imagine it’d be hard for someone to pick a hospital.

**Comment by 4kbt** [comment]
I think a map is the way to go. Trying to loop sash in.

**Comment by 4kbt** [comment]
Addresses added to the Washington sheet in support of a map. Sash is working on a map.

**Comment by ctavispost** [comment]
I'm going to change the html. Set the states, cities, and hospitals to headings. That should make it more semantic and readable.
