### ISSUE TITLE
www.findthemasks.com should redirect to findthemasks.com

### ISSUE THREAD

**Issue by patricknelson** [r-pop/findthemasks#140]
This should help reduce likelihood of duplicated content. Also ensure everyone is linking to the same URL's. The redirect should be a perm redirect (301) and should retain the request URI (i.e. if you go to https://www.findthemasks.com/give.html?state=ca it should redirect you to https://findthemasks.com/give.html?state=ca).

**Comment by r-pop** [comment]
Hi, I don't think this is necessary. I have dreamhost set up to allow both www. and bare, and the content is the same. no duplication.

**Comment by r-pop** [comment]
If you disagree please explain more thoroughly

**Comment by patricknelson** [comment]
It's just a best practice to ensure only one domain is in use; see more here: https://support.google.com/webmasters/answer/66359?hl=en

Alternatively, you could "canonicalize" with the appropriate meta tags, see: https://moz.com/learn/seo/canonicalization, e.g. 

```html
<link rel="canonical" href="https://findthemasks.com/" />
```

Unfortunately that would need to be done for every single page (with the appropriate URL plugged in). Usually it's just easier to do the domain redirect 😄

**Comment by patricknelson** [comment]
Closing; not really worthwhile, considering the testing/validation effort 😄
