### ISSUE TITLE
Incorporate map into embedded/iframe view.

### ISSUE THREAD

**Issue by patricknelson** [r-pop/findthemasks#142]
Just tracking as a ticket (as I've seen this noted before in slack).

Right now http://findthemasks.com/ incorporates the map but https://getusppe.org/give/ does not, and soon they will be getting a bunch of attention. Would be awesome for the map to be immediately visible there, as that makes it extremely easy to instantly find nearby hospitals.

**Comment by graemer** [comment]
This is done.

give.html?hide-map={true/false}
