### ISSUE TITLE
Geocoding breaks daily

### ISSUE THREAD

**Issue by susanashlock** [r-pop/findthemasks#144]
When I run the geocoding script (Apps Script, accessible from Tools > Script Editor in Google Sheets), I now get this error:

Exception: Service invoked too many times for one day: geocode. (line 38, file "Code")

According to this documentation, it might not be possible to work around in Apps Script: https://developers.google.com/apps-script/reference/maps/maps#setAuthentication(String,String)

Relevant documentation pasted below:
------
Enables the use of an externally established Google Maps APIs Premium Plan account, to leverage additional quota allowances. Your client ID and signing key can be obtained from the Google Enterprise Support Portal. Set these values to null to go back to using the default quota allowances.

Note: This method doesn't work with API keys. Additionally, please note that Premium Plan is no longer available for new customers. If you don't already have a Premium Plan license, please don't call setAuthentication(clientId, signingKey). You are able to use the Maps methods with the default quota allowances.
---------
If we can't figure out how to get quota to run from Apps Script, an alternative would be to add this logic to functions/index.js so that we do the geocoding using an API key at spreadsheet-read time.  The problem with this is that since the data.json is recreated from scratch every time, we'd be making far more geocoding calls than we need because we'd be re-geocoding data that we already have.  e.g. if we assume that we add 200 hospitals in a day, and re-run geocoding every time we add a hospital, that's ~20,000 geocoding calls / day.

I'll explore both option 1 (apps script) and credits for option 2 (updating index.js).

**Comment by susanashlock** [comment]
Update: I have a manual workaround that will work for now (running geocoding Apps Script in another account I have).  Not ideal, but it will work fine for the next day or so.

**Comment by elainemacurdy** [comment]
Have you considered using an alternative to Google (which is wicked expensive and has low rate limit thresholds)? We have a task on our backlog to switch to HERE: https://developer.here.com/products/geocoding-and-search

**Comment by susanashlock** [comment]
A third possible solution that occurred to me: have functions/index.js update the spreadsheet.  In theory, the code that's checked into public/scripts/fill-in-geocodes.js could be called from index.js.

Of course, the call to getActiveSpreadsheet() would need to be updated.  And we'd need to set up the script to use the Google Maps API.  But otherwise the logic should be similar.
