### ISSUE TITLE
Import from PPE TO CROWD-SOURCE sheet

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#16]
From email, we were sent this sheet and asked to import the entries we don't also have: https://docs.google.com/spreadsheets/d/1txEanDkIrJ5GNfSk-zlXkTlB-bQPNRN_Y69qEwmdme8/edit?fbclid=IwAR1A6TrHCQ9TttNJbb1kB6b2Xot4DCem-z6DVXUR4V5qToUboOr-50D7h6g#gid=1259409226

**Comment by cchang-adi** [comment]
I haven't figured out how to assign this to myself, but I am on it.

**Comment by cchang-adi** [comment]
Sent file to Charlie since I can't use GitHub to save my life (can you tell I'm only an electrical engineer? :P)

**Comment by r-pop** [comment]
I reached out to the sheet owner about adding credit/link and ongoing collab or integration

**Comment by cchang-adi** [comment]
This sheet is still being updated; should I submit new sites through our own Google form?

**Comment by r-pop** [comment]
If you have the time, yes!

Eventually it would be nice to automate this importing and also sync back - I am in touch with the sheet owners and may be able to discuss later this weekend.

**Comment by cchang-adi** [comment]
Ok, on it. They also differ from our form because they ask if used/dusty is ok while we ask open/unopened. That's what led to a lot of the "unsure" entries. May need to clarify what those criteria are.

**Comment by liamrosen** [comment]
Yay! Glad ya'll are in touch. I will start recommending https://findthemasks.com/ as the main resource. Right now I'm refreshing the new reddit search for "donate masks" and pointing people to resources.

**Comment by liamrosen** [comment]
By the way, there's a bunch of other sites working on the same thing here. Could be a good source for data aggregation: 

PPE Donation Project Clearinghouse
https://docs.google.com/spreadsheets/d/1OTmhM2BzMYPkdooaQeYqrDShaKHnt1ltrq3iRBPpDjU/edit#gid=0

**Comment by cchang-adi** [comment]
This sheet has reached max # of editors, so they are moving to a separate Google form as well.
