### ISSUE TITLE
DATA INPUT SWARM!

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#161]
Ok peeps, we've got a data entry blitz again. 

1. Open the new data sheet: (https://docs.google.com/spreadsheets/d/144AkG-RSnB-AntD-7B7T6IGqt3W9Dxa7es6D9LhaAXk/edit?usp=sharing)
2. Comment here to claim a group of rows. Please take in units of 20, eg "I'll take 2-20!" "I'll take 21-40!" etc. 
3. For each row, FIRST check if dupe by searching our live site at findthemasks.com (don't mess with filters, just search for the name of the hospital with ctrl-F)
4. if NOT dupe, fill in the form ( https://docs.google.com/forms/d/e/1FAIpQLSfgCpK5coPVFC6rJrE7ZhimiZuDoEaL6fo6gYqxsN_FIpJZhg/viewform) and look up missing info like address. 
note: This new data doesn't have info on whether open boxes are ok. Please write "Unsure" in that field in the form.
5. Repeat 3-4 until you're at the end of your 20.
6. Come back here and edit your comment to say you're done!
7. (Optional) claim another 20!

Thank you so much. This one-time pain lets us keep scaling and keeps ongoing data moderation much easier than if we had multiple sources, or tried to merge data into a live form-fed sheet.

**Comment by jlittenberg** [comment]
Do you want us to finish filling in the info for the places you already have the name of the clinic/hospital?

**Comment by alexisjulia** [comment]
Hi Rachel, I'll take rows 2-20. =)

**Comment by r-pop** [comment]
> Do you want us to finish filling in the info for the places you already have the name of the clinic/hospital?

Not in the sheet (you won't be able to edit it), but yes into the form (step 4). you may need to google the address of the hospital, if they didn't provide it.

**Comment by jlittenberg** [comment]
Ok thanks.

**Comment by jlittenberg** [comment]
Looks like I’m the first, I’ll take 1-20

**Comment by alexisjulia** [comment]
No I took those!

**Comment by r-pop** [comment]
@jlittenberg you aren't! please refresh, and take the next unclaimed batch.

**Comment by alexisjulia** [comment]
Hey Rachel, Shouldn't we call the hospital and get instructions and exact address for drop-off when filling in the form? Or just fill in what comes up on Google?

**Comment by alexisjulia** [comment]
Also I'll just do 21-40 so me & @jlittenberg don't replicate

**Comment by r-pop** [comment]
PAUSE THE BLITZ. @alexisjulia good catch. there was supposed to be something in that field.

**Comment by alexisjulia** [comment]
Haha okay @r-pop!

**Comment by r-pop** [comment]
Ok I think we are ready to unpause. You will need to start at the beginning. This is messier, but complete. Please let me know if you run into more issues.

**Comment by r-pop** [comment]
PS, if you want to help, unclaimed rows start at 40 and we are open for data entry!

**Comment by alexisjulia** [comment]
> Also I'll just do 21-40 so me & @jlittenberg don't replicate

Done!

**Comment by alexisjulia** [comment]
I'll do 41-60 now

**Comment by amchassanoff** [comment]
I'll take 61-80

**Comment by fquerdasi** [comment]
I'll take 81-100

**Comment by amchassanoff** [comment]
> I'll take 61-80

note there are multiple urgent care chains sometimes -- i'm picking the first address unless other ideas

**Comment by fquerdasi** [comment]
> Does dupe mean duplicate? I'll take 81-100

What should we do if we can't find some of the info on the form?

**Comment by amchassanoff** [comment]
> > Does dupe mean duplicate? I'll take 81-100
> 
> What should we do if we can't find some of the info on the form?

If it supplies I've been checking "other" and writing "not specified"
If it's address, i've been picking the first one
If it's open boxes, write in "unsure"

**Comment by fquerdasi** [comment]
Done with 81-100. Note that in most cases I couldn't find specific instructions for delivery/drop-off.

**Comment by per1234** [comment]
I'll take 101-120!

**Comment by supertriceratops** [comment]
I'll take 121-140

**Comment by staceyhanson** [comment]
Working on 141-160

**Comment by per1234** [comment]
I'll take 161-180!

**Comment by per1234** [comment]
I'll take 181-200!

**Comment by supertriceratops** [comment]
Whoops, I accidentally entered in two that were already on the site:
- Edward Hospital (in Naperville, IL)
- AdventHealth Hendersonville

There are some data issues with a few of mine serious enough that I didn't want to enter them:
- I skipped 122 since it is for Kaiser Los Altos, and as far as I can figure out there is no Kaiser in Los Altos. 
- I skipped row 124 for "Kaiser Permanente GA Region" since this is not one specific hospital, and I could not find a specific Kaiser Permanente hospital in Georgia that clearly advertised mask donations on their site after ~10 minutes of searching.
- I skipped Row 127, which is as far as I can tell an individual person (visiting nurse). Should that make it over to the site?
- I skipped Row 131, which is for a restoration (e.g. water/fire damage) company, not a hospital (!).

Also, when doing this I noticed Kaiser Permanente Santa Clara on the live site is misfiled since the address is in San Francisco.

**Comment by per1234** [comment]
I'll take 201-220!

**Comment by per1234** [comment]
I'll take 221-240!

**Comment by per1234** [comment]
I'll take 241-260!

**Comment by per1234** [comment]
I'll take 261-280!

**Comment by per1234** [comment]
I'll take 281-300!

**Comment by per1234** [comment]
I'll take 301-314!

**Comment by per1234** [comment]
The spreadsheet is now finished.

**Comment by amchassanoff** [comment]
you all are AWESOME

**Comment by alexisjulia** [comment]
> I'll do 41-60 now

Done!

**Comment by r-pop** [comment]
You all are wonderous beings. If you would like a mention on findthemasks.com/whoweare.html, I would be delighted to add you there. Just let me know what name or username you want displayed, and (optionally) where to link it to .

**Comment by supertriceratops** [comment]
You can add my name "Caitlin Sadowski" linked to https://research.google/people/CaitlinSadowski/

Also, pasting my update above here to make sure you saw it:

> I'll take 121-140. Done, except:
> 
> Whoops, I accidentally entered in two that were already on the site:
> 
> * Edward Hospital (in Naperville, IL)
> * AdventHealth Hendersonville
> 
> There are also some data issues with a few of mine serious enough that I didn't want to enter them:
> 
> * I skipped 122 since it is for Kaiser Los Altos, and as far as I can figure out there is no Kaiser in Los Altos.
> * I skipped row 124 for "Kaiser Permanente GA Region" since this is not one specific hospital, and I could not find a specific Kaiser Permanente hospital in Georgia that clearly advertised mask donations on their site after ~10 minutes of searching.
> * I skipped Row 127, which is as far as I can tell an individual person (visiting nurse). Should that make it over to the site?
> * I skipped Row 131, which is for a restoration (e.g. water/fire damage) company, not a hospital (!).
> 
> Also, when doing this I noticed Kaiser Permanente Santa Clara on the live site is misfiled since the address is in San Francisco. Not sure how to fix this.

**Comment by r-pop** [comment]
@supertriceratops I did see it, and the data mods read it. we are underwater with comms since this is a rapid response project. Thank you!
