### ISSUE TITLE
Filter functionality for donation lists

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#2]
Users should be able to filter by state, and materials accepted. (N95, surgical, booties, goggles, etc) and (opened box, unopened box).

**Comment by eZanmoto** [comment]
I've implemented this in https://github.com/r-pop/findthemasks/pull/46, please let me know what you think.

**Comment by jianshen** [comment]
Ooh @eZanmoto your filters look great! @r-pop feel free to ignore my PR. Great job putting all this together btw.

**Comment by eZanmoto** [comment]
Thanks!
