### ISSUE TITLE
Data: Categorizing recipients

### ISSUE THREAD

**Issue by 4kbt** [r-pop/findthemasks#206]
It is very likely to be useful in the future to have some metadata on our recipients list. In particular, it seems useful to do some broad categorization.

Someone can 

1. Skim through the data and develop a tentative list of categories. Ideas include (Hospital, Nursing Home, Doctor's Office, Rehab, Mental Health, Addiction, Pharmacy, Dentist, EMS, Public Health)

Delivery-categorization may also be useful: (At-institution, residential drop-off, off-site dropoff)?

2. Run through the data, either on-line or off-line (no-delete policy should make an off-line merge possible), and categorize the entries. 

Automated tools may be able to handle the bulk of the legwork.

**Comment by 4kbt** [comment]
All the #data team needs to make this happen are new allocated columns in Form Responses. Could we get a "Category" column or three allocated for this purpose?

**Comment by cchang-adi** [comment]
Suggested category: Clinic. Smaller than a hospital (no departments), includes Urgent Cares as well.

**Comment by graemer** [comment]
Done. Added Category with items enumerated above.

**Comment by cchang-adi** [comment]
Sorry to come back to a closed issue - forgot one category, Dialysis Center. We include those because people can't stop going to them.
