### ISSUE TITLE
Migrate to reading addresses from autogenAddress field in spreadsheet

### ISSUE THREAD

**Issue by susanashlock** [r-pop/findthemasks#215]
To speed up address data moderation and to make sure that we preserve a user's original address input, I propose the following changes:

* Change our data pipeline to read from autogenAddress instead of address for geocoding.   Website would need to be updated to read from this field as well, either at json-generation time or at load time.
* Instead of having "quick-mod" operators copy the autogenAddress field into the address field, have them to do a quick sanity check on the user-entered address and extract any info that should go into the 'instructions' column but otherwise not touch addresses during the moderation process.  Someone focused on address moderation could do sanity-checks by scrolling through the autogenAddress column and making any changes to that data if needed.

**Comment by awong-dev** [comment]
I think this is done. Closing.
