### ISSUE TITLE
Add "who are we" page

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#23]
Some concerns raised on twitter that the source of this work is not clear. I will add a short who we are page. Would like to give all contributors credit - please let me know if I may post your name or handle or if you'd like to remain anonymous.

@awong-dev @ctavispost @leee @shahronak @4kbt @graemer

**Comment by r-pop** [comment]
Fixed! @leee I didn't list you, if you want to be listed just let me know how to credit you - Name and (optional) link.

**Comment by leee** [comment]
I appreciate it 🙂Sorry I haven't contributed much other than that single hospital group listing, not much brainspace cycles at the moment. I'll submit a PR for posterity.
