### ISSUE TITLE
Add embedded map view 

### ISSUE THREAD

**Issue by shahronak** [r-pop/findthemasks#28]
**API costs:**
Geocoding API to convert addresses to lat/long: _0.005 USD per call_
Google Maps JS API per map load cost: _0.0056 USD per load  (at 100,001 - 500,000 monthly volume)_

We can call the geocoding API once per new form entry as part of the backend conversion to JSON. Let's say 200 hospitals. This cost would be negligible ($1)

Current requests to the page is ~40k after 1 day of release. Assuming traffic is ~500,000 map loads per month. Cost would be $2,800.

**Comment by shahronak** [comment]
Feel free to assign this one to me, I'm going start taking a look.

**Comment by r-pop** [comment]
@4kft knows a gmaps SWE who may be able to help. Not sure if there is public interest/crisis response capacity available for less.

**Comment by patricknelson** [comment]
I think this ticket can be closed as a map is now embedded already on the site using cached lat/long coordinates already stored in the source data ([feed](https://docs.google.com/spreadsheets/d/1GwP7Ly6iaqgcms0T80QGCNW4y2gJ7tzVND2CktFqnXM/edit#gid=2027792507)).
