### ISSUE TITLE
design: favicons would be nice to have

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#31]

**Comment by leee** [comment]
I just need to confirm attribution/licensing requirements, but I think this will work since it's from Twitter and they're theoretically free for use: https://favicon.io/emoji-favicons/face-with-medical-mask/

**Comment by r-pop** [comment]
I love it. And maybe this helps:
https://blog.twitter.com/developer/en_us/a/2014/open-sourcing-twitter-emoji-for-everyone.html

**Comment by leee** [comment]
Works for me, and per https://twemoji.twitter.com/

> As an open source project, attribution is critical from a legal, practical and motivational perspective in our opinion. The graphics are licensed under the CC-BY 4.0 which has a pretty good guide on best practices for attribution.

> However, we consider the guide a bit onerous and as a project, will accept a mention in a project README or an 'About' section or footer on a website. In mobile applications, a common place would be in the Settings/About section (for example, see the mobile Twitter application Settings->About->Legal section). We would consider a mention in the HTML/JS source sufficient also.

So I'll keep this simple and take the files, dump them into root, and add the appropriate `head`s to the two html files for the time being.

**Comment by r-pop** [comment]
Or you could put the license info in the project readme on github! if i
have to be the one to do that, lmk.
