### ISSUE TITLE
SEEKING:   Volunteers to publish your list in a Global Searchable Directory

### ISSUE THREAD

**Issue by ray-odoo** [r-pop/findthemasks#39]
https://helpfulengineering.odoo.com/members

Is there any interest?

**Comment by ray-odoo** [comment]
https://helpfulengineering.odoo.com/register - via a simple web page you can enter a NEED or HAVE entry.

**Comment by r-pop** [comment]
Not able to adopt that. We are keeping it simple and focusing on collecting data about what hospitals will accept.

**Comment by ray-odoo** [comment]
OK.  Thanks for considering.  Can I ask what isn't simple about this method of collecting data about what hospitals will accept?

**Comment by ray-odoo** [comment]
![image](https://user-images.githubusercontent.com/41073831/77220274-c274ee00-6afb-11ea-8679-a5fac3a3af62.png)

**Comment by ray-odoo** [comment]
![image](https://user-images.githubusercontent.com/41073831/77220281-d587be00-6afb-11ea-827b-3e8241cbb9b7.png)

**Comment by r-pop** [comment]
We already have something in use that is meeting our needs.
