### ISSUE TITLE
THE GREAT DATA BACKFILL

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#42]
Hello volunteers! This need is short term and appropriate for detail-oriented folks without coding experience. We are moving to an automatic publishing pipeline that relies on our google form directly to build the site, but we currently have a lot of valuable listings on the site that didn't go through the form at all. We have to put this info into the form so that we don't lose it in the move.

Between now and mid-day Saturday March 21, the task is:
1. Comment here to claim a state and let others know not to start on it.
2. Read through the live findthemasks.com site section for your state
3. For each hospital, check if it is in our sheet already (use ctrl-F to search): https://docs.google.com/spreadsheets/d/1GwP7Ly6iaqgcms0T80QGCNW4y2gJ7tzVND2CktFqnXM/edit?usp=sharing
4. If it is not there, submit it through our public google form: https://docs.google.com/forms/d/e/1FAIpQLSfgCpK5coPVFC6rJrE7ZhimiZuDoEaL6fo6gYqxsN_FIpJZhg/viewform

That's it!

**Comment by melaniebcohen** [comment]
I can take Washington!

**Comment by melaniebcohen** [comment]
That went faster than expected. I'll do Oklahoma through Washington DC and call it a night. Let me know if you need more support tomorrow, happy to help.

**Comment by skimekerr** [comment]
I'll do California.

**Comment by unruthless** [comment]
I'll do Maine and Massachusetts.

**Comment by unruthless** [comment]
> I'll do Maine and Massachusetts.

Done. There was one entry for Mass that will likely break the formatting of any page attempting to render it. (Partners Healthcare, they're looking for testing kits).

**Comment by r-pop** [comment]
@unruthless thank you. I saw that one. Members of the public won't have that and we may take it down in the move.

**Comment by marcpopMSFT** [comment]
Looks like Michigan through Mississippi are up for grabs so I'll do those

**Comment by skimekerr** [comment]
> I'll do California.

@r-pop - I'm seeing inconsistency in the Hospital Name info for the Valley Medical Center Foundation on the website and the Santa Clara Valley Medical Center entry in the Gsheet (row 9). I don't have edit access to the spreadsheet to update. I'm thinking the spreadsheet needs to be updated to say Valley Medical Center Foundation.

**Comment by marcpopMSFT** [comment]
Looks like MS was already covered (and actually shows up twice in the spreadsheet).  I looked up providence in Montana's address from the web.

**Comment by skimekerr** [comment]
> I'll do California.

Done.

**Comment by skimekerr** [comment]
I'll do Missouri & Nevada now.

**Comment by r-pop** [comment]
> > I'll do California.
> 
> @r-pop - I'm seeing inconsistency in the Hospital Name info for the Valley Medical Center Foundation on the website and the Santa Clara Valley Medical Center entry in the Gsheet (row 9). I don't have edit access to the spreadsheet to update. I'm thinking the spreadsheet needs to be updated to say Valley Medical Center Foundation.

I just gave you access and agree with your proposed edit.

**Comment by r-pop** [comment]
> Looks like MS was already covered (and actually shows up twice in the spreadsheet). I looked up providence in Montana's address from the web.

Thank you! Some of the states may have only ever had entries from the form so if there's no entry needed that's not weird.

**Comment by skimekerr** [comment]
Looks like the last state in the website not claimed is New York. I've got it now.

**Comment by skimekerr** [comment]
> Looks like the last state in the website not claimed is New York. I've got it now.

@r-pop - FYI - Elmhurst Hospital in NY is requesting ventilators. Probably not a thing the general public would have on hand... but might be a good idea to keep these types of asks on here (including testing kits comment above)? Maybe if there's another hospital or medical professions looking at this and they. have spares that can be moved between hospitals?

**Comment by alexisjulia** [comment]
I'll do Oklahoma & Oregon =)

**Comment by skimekerr** [comment]
@r-pop - you might want to options to the equipment that's being accepted. Here's some that came up multiple times for me. 

hand sanitizer
gowns

**Comment by skimekerr** [comment]
> I'll do Oklahoma & Oregon =)

@alexisjulia - Oklahoma through Washington DC was grabbed by @melaniebcohen earlier. Might want to check to see if that's done already. 

I'm pretty sure that all the states are now complete, but a sanity check of any that's missing from this popcorn style of grabbing states would be appreciated.

**Comment by alexisjulia** [comment]
@skimekerr ha! okay was just about to report "they're all in there!" 

I think all the popcorn has been grabbed, time for red vines

**Comment by awong-dev** [comment]
FYI, someone still needs to walk through the "moderated" tab and put an "x" in the approve column for every verified entry for it to show up.  Currently items 47 through 114 are not verified/approved.  Tagging @r-pop and @graemer for visibility.

**Comment by skimekerr** [comment]
What does it mean to "Verify" or "Approve" the items? Is it cleaning up the data and checking that the data is accurate? 

Also, some of the earlier data in the spreadsheet seems to be poorly formatted and may need to be cleaned up? Is that something that needs to happen too?

**Comment by r-pop** [comment]
Great questions, we haven't formalized that process but that's our next need - want to take it on? 

I just went through and tried to:
- sanity check the entries - eg if there was a longwinded description that could be clearer, edit it down in "Form response 1". 
- make sure there was one entry per donation site, and picked the more thorough or legit looking one
- cleaned city data where necessary (delete trailing space) to make sure only one entry per city appears in generated

@4kbt is currently fixing addresses in Form Responses 1 per #47

**Comment by r-pop** [comment]
@skimekerr see previous. Also, what I actually did just now was very liberally put the 'x' in Column A of "moderated" tab, then hit a URL that forces reload of the data into the automated html (https://us-central1-findthemasks.cloudfunctions.net/reloadsheetdata), then scroll through the generated page looking for dupes.

This "test in prod" is more palatable now before we've cut over, not sure if we'll want to do it that way after we launch the automated index.

**Comment by cchang-adi** [comment]
Add another option for accepted items: disinfecting wipes

**Comment by skimekerr** [comment]
> Can we add another option for items? I see a lot of "disinfecting wipes" "thermometers"

I've also seen a lots of requests for:
hand sanitizer
gowns

**Comment by r-pop** [comment]
@skimekerr @cchang-adi added gowns, hand sanitizer, disinfecting wipes, thermometers to the form!

**Comment by skimekerr** [comment]
I'm going to go through the "Form Responses 1" and clean up the "Drop Off Instructions" data that needs it.

**Comment by skimekerr** [comment]
@r-pop - We have conflicting info for Swedish Issaquah equipment and open vs. closed boxes. If you agree, I'll combine the equipment list and say they are accepting open boxes and the hospital can decide how to triage any open boxes if they don't actually want them.

**Comment by r-pop** [comment]
@skimekerr SGTM
