### ISSUE TITLE
Coordinate with "PPE Supplies Needed" and "Donate PPE" to avoid duplicating work

### ISSUE THREAD

**Issue by liamrosen** [r-pop/findthemasks#50]
Looks like there are already two sheets/resources out there with similar information:
[PPE Supplies Needed](https://docs.google.com/spreadsheets/d/1txEanDkIrJ5GNfSk-zlXkTlB-bQPNRN_Y69qEwmdme8/htmlview?sle=true) and https://www.donateppe.org/. 

It would be a good idea to merge everything into one nice resource.

**Comment by r-pop** [comment]
Recorded donateppe in #15. Merging the suggestion to collab into the issue tracking progress.
Duplicate of #16
