### ISSUE TITLE
iOS Safari: filters don't show up

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#56]
They are working on iOS Chrome and Android Chrome.

@eZanmoto can you take a look?

**Comment by eZanmoto** [comment]
Thanks for flagging this, I'll take a look. Thanks!

**Comment by eZanmoto** [comment]
I've taken a quick look on iOS Safari and Mac Safari but it's showing up on both for me, do you have more details on this? Is AL showing up directly below "List of donation sites", or is some of the filter information showing up? Please also provide a screenshot of what you're seeing where the filters are supposed to be as well, if that's alright, thanks!

**Comment by cjimmy** [comment]
These show up and work for me on iOS (Safari + Chrome), and Android (Chrome)

**Comment by r-pop** [comment]
We think this was a caching issue - it was working for graemer when I spoke
to him recently. you can close.
