### ISSUE TITLE
Need to automate new donation site workflow

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#6]
Current workflow:
- receive gform
- call hospital if info is incomplete (it usually is)
- manually edit index.html, push, and deploy

Better ideas:
- automatic update from form (but I really worry about moderation - people have put in long random comments, lots about mask sewing which is not what we're doing with this site)
- publish form responses as google sheet and make viewable (but also need a moderation step if possible - is it?)
- streamlining of the current workflow that would scale to a larger number of less technical volunteers without high potential for mistakes in prod

**Comment by 4kbt** [comment]
Perhaps it would be useful to use a spreadsheet to coordinate calling/sourcing information. 

A mock-up example is here: https://docs.google.com/spreadsheets/d/1edSpWG2YJyhJ-9gc8NOcXngO5EU7wNAjf2RKo9xYhzk/edit#gid=0

**Comment by 4kbt** [comment]
I believe that form responses can be moderated somehow. Will check.

If this site catches on, we have to make sure we don't spam the hospitals with callers.

**Comment by 4kbt** [comment]
I am going to backfill the phone numbers for this Sheet now. Will be slow, but can give callers some structure.   Feel free to email me email addresses of trusted editors.

**Comment by 4kbt** [comment]
Phone numbers now filled in for Washington.

**Comment by 4kbt** [comment]
Starting work on New York State. Source data are worse, so it is going to be a little slower.

**Comment by DriftGuru** [comment]
Thoughts around a chatbot that could automatically pull all this info in from a database into the bot... https://video.drift.com/v/absBr9Bp3R7/ I built it out real quick.  If I spent some time and we had a database we could update and pull the info faster.

**Comment by 4kbt** [comment]
NYS is slow, but filling in here: https://docs.google.com/spreadsheets/d/1qUY-uF2eBmFjPtUZ5wGvH4Lslr7pJ6O28IWRhso1FbY/edit?usp=sharing

**Comment by DriftGuru** [comment]
I just reached out to the COO of Zocdoc.  May be able to get a full list in a database we need.

**Comment by r-pop** [comment]
@DriftGuru the hardest part of getting the data is getting safe dropoff instructions. We don't want people wandering in with masks during a crisis. We also need to find out which sites are accepting opened packs and which aren't. Normal procedure is no - but I think soon everyone will take what they can get. Meantime it's complicated. 

@4kbt thank you! My wife has made most of the Seattle calls so far and she went through and marked the ones she tried that didn't give definitive info (some said they will call her back tomorrow). A larger todo that would be appropriate for someone not that technical but very organized and good at comms would be to take your spreadsheets and organize volunteers to call and get the info. We may need a slack...

**Comment by 4kbt** [comment]
NYS is done. Will require some thoughtful deduplication

**Comment by 4kbt** [comment]
Pinged one of the better social-organizers I know, cc'ed @r-pop .

**Comment by 4kbt** [comment]
Oregon sheet created, haven't yet added phone numbers: https://docs.google.com/spreadsheets/d/1Pr0pw8EOs6d1oRKcmgarYT2Pi3gi5aEng2JS823qHnY/edit#gid=0

**Comment by yauwong** [comment]
I can make some calls tomorrow if someone wants to give me a list of a few places. Unless there are a ton of hands on deck, I would suggest first trying to get one hospital identified per state plus one hospital per major city, before we go through the task of contacting all of the hospitals in the entire country.

**Comment by r-pop** [comment]
Thanks Yau! One per state plus every major city is a very achievable goal for tomorrow's calls. So far the info has been pretty random (form submissions and things people tagged me in on social media). My wife called the largest ten Seattle hospitals too. But yes - breadth before depth!

**Comment by yauwong** [comment]
Great! I’ll work on that in the morning. 

I found this list on Twitter that someone else is working on. It adds a few additional hospitals to our list: https://docs.google.com/spreadsheets/d/1txEanDkIrJ5GNfSk-zlXkTlB-bQPNRN_Y69qEwmdme8/htmlview#gid=1259409226

**Comment by r-pop** [comment]
Thank you! I opened #16 for that and will work on it tomorrow unless a volunteer dev picks it up.

**Comment by yauwong** [comment]
💪(elbow bump in lieu of a high five)

**Comment by yauwong** [comment]
So I was thinking emails would be a lot faster for reaching more places. I drafted something. Feel free to copy or give comments: 

Hi,

I am putting together a list of hospitals and clinics that are need of face masks and other personal protective equipment donations. The list will be shared on findthemasksks.com for individuals and businesses to use. If your hospital is looking for these donations, can you please fill out the information below so we can add you to our list?

1. What specifically are you accepting? (E.g. N95 masks, surgical masks, isolation masks, disposable booties, safety goggles, etc.) Are open boxed items acceptable?
2. Where are donations being accepted? 
3. Are there any specific drop-off instructions? 
4. Can donations be mailed in? If so, to where and addressed to whom?

Thanks so much!

**Comment by r-pop** [comment]
@yauwong for sure, if you can find email contacts! The HCW I spoke with (on twitter right before launch) rec'd using the charge nurse as decision maker, which generally requires phone call from the outside. But if you have contact info or can find it, please go ahead!
 
Edits:
- typo in the URL: findthemasks.com
- please state the purpose of the site as encouraging the public to donate small quantities of PPE they may have - so that they know we are not likely to come through with a shipment.
- please ask about how the public can safely and properly drop off donations (vs specific which is, ironically, a more vague word in this context!)

**Comment by r-pop** [comment]
To record more clearly, the info gathering priority is not to call every hospital in a geo (Charlie's sheets), it is to have a broad coverage on the site to better serve members of the public across the country. Charlie, appreciate the effort, and these may be of use later in the project when we have that capacity.

**Comment by yauwong** [comment]
Sounds good. I sent out about 20 emails this morning and am submitting responses on the findthemasks.com form. Will send out more throughout the day.

**Comment by r-pop** [comment]
Awesome, that's perfect!

**Comment by r-pop** [comment]
This has become obsolete, I'll open a new issue for outreach to states/cities not yet covered.
