### ISSUE TITLE
Extended url-text causes horizontal-scrollability on chrome-android

### ISSUE THREAD

**Issue by 4kbt** [r-pop/findthemasks#65]
With the new version of the site (1406 Pacific, March 21), when viewing on Chrome-android (pixel 3a), the site can be scrolled laterally.

It appears that long url strings are the cause.  Firefox-android does not do this. 

This bug may be addressed in the future by collapsing the urls back into links.

**Comment by cchang-adi** [comment]
Verified just now that automated site plays nice with <a> link tags. Will go back and edit plain text links to be <a href="> unless there are technical objections to this change.
