### ISSUE TITLE
Stand up basic monitoring

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#85]
Would like to be alerted if the site goes down, the list of donation locations does not show up, or (stretch goal) one of the data fields stops populating.

**Comment by eZanmoto** [comment]
I recommend https://uptimerobot.com/ which I can set up, I'll just need email addresses to notify, or it can be set up to notify on Slack or Twitter (no Facebook Messenger, unfortunately). We can set up a HTTP(S) monitor for the main site and a keyword monitor for `data.json` to make sure that it's populated. It will be using five minute intervals for the free tier, but they could be contacted to see if they would provide their 1 minute monitoring for the cause.

**Comment by r-pop** [comment]
That sounds perfect. We are migrating to slack tomorrow anyway so let's
have it notify there.

**Comment by r-pop** [comment]
Also I can just pay for the 1 min tier.

**Comment by eZanmoto** [comment]
Perfect, I've set that up to notify the `#uptime-robot` channel in the case that https://findthemasks.com becomes unreachable or `data.json` is blank. I think we can discuss the other tiers further on Slack.
