### ISSUE TITLE
Manually update donation sites

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#9]
Hi all, I need a break from manual HTML updates. 

Here is where the form submissions come in, and I've processed through 10: https://docs.google.com/spreadsheets/d/1GwP7Ly6iaqgcms0T80QGCNW4y2gJ7tzVND2CktFqnXM/edit?usp=drive_web&ouid=106808033963993184667

If you want to try to edit index.html to include a new site, go ahead. Awong or I can approve your merge.

I'm going offline for a little bit to take a break, but will deploy any changes when I come back.

**Comment by r-pop** [comment]
@4kbt if you have cycles, here is the sheet. 24+ are new. Please call what you're doing here, and submit a PR when they're added!

**Comment by 4kbt** [comment]
Will take number 26, St. Clare, as a test to make sure that formatting goes well.

**Comment by 4kbt** [comment]
Will handle rows 27-30.

**Comment by 4kbt** [comment]
Unclear how to handle hospital 31. Will handle 32-35.

**Comment by 4kbt** [comment]
Addressing 36 and 37.

**Comment by 4kbt** [comment]
Addressing 38 and 40. 39 is not a hospital.

**Comment by 4kbt** [comment]
Tackling hospital 41.

**Comment by 4kbt** [comment]
Will get 42 in this commit, too.

**Comment by yauwong** [comment]
I've received an update to Boston Medical Center. Let me know if someone can change this:
For mailing, same address, with additional instructions:
Ask that they please put a note in the box specifying that it is a donation. Make sure that they provide their name, email, and  mailing address, along with the monetary value of their donation (for policy reasons). 

Updated PPE List: Surgical Gloves
Gowns (Fluid resistant or not)
Disposable Face shields
Thermometers
N95 respirators mask
Masks (surgical/cloth)
Positive Airway Purifying Respirator (PAPR) disposable/replacement parts (hoods, battery pack, tubing)
Hoods

**Comment by r-pop** [comment]
I am doing the Boston Med Center update (in the sheet and the html) now, and then let's stop doing manual updates. We'll focus tomorrow on data backfill (I will open a new issue) and then cut over to the automatic pipeline!
